export enum Environment {
  HTTP_PORT= 'HTTP_PORT',
  GET_HEALTH_CHECK_ROUTE = 'GET_HEALTH_CHECK_ROUTE',
  WS_ROUTE = 'WS_ROUTE',
  MOCKED_TOKEN = 'MOCKED_TOKEN',
  WS_USER_SERVICE_URL = 'WS_USER_SERVICE_URL',
  WS_ROOM_SERVICE_URL = 'WS_GAME_SERVICE_URL',
}
